import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillGithub} from 'react-icons/ai'
import Image from 'next/image';
import tarikPic from "../public/tarik-pic.png"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tarik Ozturk Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons'>Tarik Ozturk</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Tarik Ozturk</h2>
            <h3 className='text-2xl py-2'>Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Hi, I am a developer with a passion for creating efficient solutions to complex problems. 
              My interest in solving problems developed through life science while studying for my B.S. in 
              Physiotherapy and Rehabilitation. Then I started learning programming as a hobby, which led a 
              career change. I am currently studying Computer Programming at Seneca College in Toronto. During 
              my study, I focused on data structures and algorithms, object oriented programming, database management, 
              backend and frontend web development, software analysis and design. I wish to continue working with 
              passionate teams of talented developers to create technology that benefits its users by improving their 
              daily health and everyday life.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillGithub />
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-84 md:w-84">
              <Image src={tarikPic} layout="fill" objectFit="cover" />
            </div>
        </section>


        
      </main>
    </div>
  );
}
